// ══════════════════════════════════════════════════════════════════════════════
// DCC CHARACTER DAG — DATA FILE
// Books 1–6 (The Eye of the Bedlam Bride)
// All characters and relationships live here. App.jsx is pure UI.
// ══════════════════════════════════════════════════════════════════════════════

export const NODES = [
  // ── BOOK 1 PARTY ──
  { id: "carl", label: "Carl", book: 1, faction: "PARTY", role: "Crawler", x: 500, y: 310,
    desc: "Coast Guard vet, 27. Partners with his ex's cat through the dungeon. Chooses Primal race / Compensated Anarchist class. Specialist in explosives and improvisation. Earns catchphrase 'Goddamnit, Donut.' Political thorn in Borant's side. Discovers the Dungeon Anarchist's Cookbook on Floor 4 — a secret artifact passed between crawlers across seasons." },
  { id: "donut", label: "Princess Donut", book: 1, faction: "PARTY", role: "Mage", x: 360, y: 190,
    desc: "Carl's ex's prize show cat. Absurdly high Charisma. Former Child Actor class. Her crown places her in Blood Sultanate succession. Becomes a galactic celebrity. On Floor 4 she begins maturing into a real strategist." },
  { id: "mordecai", label: "Mordecai", book: 1, faction: "PARTY", role: "Trickster", x: 220, y: 310,
    desc: "Racetrack Changeling NPC, incubus form on Floor 3. Becomes Donut's manager. Deeply knowledgeable, keeps secrets. Gets banished from the Dungeon for days on Floor 4 after attacking the fan-box presenter who has a history with him." },
  { id: "mongo", label: "Mongo", book: 1, faction: "PARTY", role: "Companion", x: 220, y: 160,
    desc: "Donut's velociraptor. Ferociously loyal. Donut can Clockwork Triplicate him into 3 copies from Book 2 onward." },
  // ── BOOK 2 PARTY ──
  { id: "katia", label: "Katia Grim", book: 2, faction: "PARTY", role: "Juggernaut", x: 640, y: 190,
    desc: "Icelandic art professor. Doppelganger / Monster Truck Driver class. Joins in Book 2, ten levels behind but catches up fast. In Book 3 she becomes a popular and capable crawler in her own right — Carl exploits her race and class creatively to give her a steel-loaded backpack she can morph into armor. Eventually leads Team Katia." },
  // ── BOOK 1 MEADOW LARK ──
  { id: "brandon", label: "Brandon Andrews", book: 1, faction: "MEADOWLARK", role: "Survivor", x: 750, y: 270,
    desc: "Meadow Lark maintenance worker. Natural leader. Giant magical hammer. Dies heroically holding off a monster horde." },
  { id: "chris", label: "Chris Andrews", book: 1, faction: "MEADOWLARK", role: "Survivor", x: 850, y: 340,
    desc: "Brandon's brother. Survives into Book 3. Odette cryptically tries to warn Carl about him mid-Floor 4, but is muted by the system before she can finish." },
  { id: "imani", label: "Imani", book: 1, faction: "MEADOWLARK", role: "Healer", x: 760, y: 390,
    desc: "Meadow Lark caretaker, healer class. 12 player-kills (claims mercy killings). One of Carl's most trusted allies. Helps plan and execute the major Floor 5 operation alongside Carl. On Floor 8 all four of her squad mates die, leaving her to ride the portal up to Floor 9 alongside Carl and Donut." },
  { id: "yolanda", label: "Yolanda Martinez", book: 1, faction: "MEADOWLARK", role: "Caretaker", x: 870, y: 430,
    desc: "Meadow Lark caretaker. Tries to stop Jack. Dies in the Rage Elemental chaos. The guild 'Safehome Yolanda' is named in her memory." },
  { id: "elle", label: "Elle McGibbons", book: 1, faction: "MEADOWLARK", role: "Resident", x: 960, y: 270,
    desc: "99-year-old Meadow Lark resident. Hits on Carl. Transforms into the powerful Frost Maiden on Floor 3. By Book 3 she tries out new catchphrases, landing on 'Stay Frosty.'" },
  { id: "jack", label: "Jack", book: 1, faction: "MEADOWLARK", role: "Resident", x: 960, y: 380,
    desc: "Elderly resident with dementia. Urinates in the dungeon corridor, summoning a Level 93 Rage Elemental. Dies in the aftermath." },
  { id: "agatha", label: "Agatha", book: 1, faction: "MEADOWLARK", role: "Survivor", x: 860, y: 490,
    desc: "Mysterious homeless woman. Set fire to Meadow Lark's kitchen, forcing the evacuation. Descends alone. Her true nature heavily hinted in later books." },
  // ── BOOK 1 OTHER CRAWLERS ──
  { id: "li_jun", label: "Li Jun", book: 1, faction: "CRAWLERS", role: "Crawler", x: 500, y: 165,
    desc: "Asian crawler. Rescued by Carl from Prince Maestro's death show. Kung-fu style martial artist — one of the toughest crawlers in the top ten by Floor 3. On Floor 8, jumps to protect Carl when Shi Maria possesses him. She stabs out his eye with a tattoo needle. Li Jun later receives a mechanical replacement eye from a loot box on Floor 9." },
  { id: "li_na", label: "Li Na", book: 1, faction: "CRAWLERS", role: "Crawler", x: 610, y: 130,
    desc: "Crawler in Li Jun's group. Saved by Carl. Grows into a strong fighter. Named as a signatory on Carl's Floor 5 battle plan in the Cookbook. On Floor 8 she is part of the coalition that fights Ysalte and Amayon." },
  { id: "zhang", label: "Zhang", book: 1, faction: "CRAWLERS", role: "Crawler", x: 720, y: 130,
    desc: "Third member of the Asian crawler group. Group's manager figure. All three rescued from near-death by Carl. In love with Li Na (Li Jun hasn't noticed)." },
  // ── BOOK 2 CRAWLERS ──
  { id: "hekla", label: "Hekla", book: 2, faction: "CRAWLERS", role: "Crawler", x: 720, y: 65,
    desc: "Leader of Brynhild's Daughters, top-2 leaderboard at end of Book 2. Contacts Carl to hand off Katia. In Book 3 her husband is shown dying from a cactus mob. Her arc grows darker — Odette warns Carl about her but is muted before finishing. Her true agenda with Katia becomes clear in later books." },
  { id: "lucia", label: "Lucia Mar", book: 2, faction: "CRAWLERS", role: "Crawler", x: 620, y: 65,
    desc: "#1 leaderboard at end of Book 2. Lajabless race — beautiful by day, skull-faced by night. By Book 3 she is clearly overpowered; Mordecai suspects she accepted a deal to erase how she killed two admins. Kills Ifechi (Florin's partner) in a spell-reflection trap on Floor 4." },
  { id: "quan", label: "Quan CH", book: 2, faction: "CRAWLERS", role: "Crawler", x: 500, y: 65,
    desc: "Opened his celestial box before Borant's VETO in Book 2. In Book 3 he has a celestial item granting flight, lightning bolts, and a full damage shield. Tries to interfere with Carl's Floor 4 endgame. On Floor 8 he follows Carl and Donut to Cuba, steals both stairwell keys in a three-way card battle. Killed by Donut. Final words: 'She'd be ashamed of what I've become.'" },
  // ── BOOK 3 NEW CRAWLERS ──
  { id: "miriam", label: "Miriam Dom", book: 3, faction: "CRAWLERS", role: "Shepherd", x: 420, y: 50,
    desc: "Italian goat farmer, Shepherd class. Entered with 15 boer goats — herded them through the first two floors. Becomes a top-10 crawler. Turned vampire in Book 3's Floor 4. Despite being vegetarian, she refuses to drink her goats' blood (the dungeon finds this hilarious). Deep maternal bond with Prepotente. Sacrifices herself at dawn on Floor 5 to free Prepotente from the Ring of Divine Suffering debuff — her death cures all vampires on the floor." },
  { id: "prepotente", label: "Prepotente", book: 3, faction: "CRAWLERS", role: "Aerialist", x: 310, y: 50,
    desc: "Miriam's beloved goat, transformed into a bipedal Caprid / Forsaken Aerialist by a pet biscuit on Floor 3. Name means 'arrogant and bossy' in Italian — accurate. Screams constantly and for no apparent reason. Starts out as a weird jerk, matures greatly. Terrifyingly smart underneath the chaos. After Miriam's death he's essentially unmoored and borderline dangerous. Eventually develops a frenemy relationship with Carl." },
  { id: "florin", label: "Florin", book: 3, faction: "CRAWLERS", role: "Crawler", x: 840, y: 60,
    desc: "Crawler from France who spent time in Africa, speaks with an Australian accent. Ex-mercenary. Partners with Ifechi early. In Book 3 on Floor 4, Lucia Mar uses a spell-reflection trap that causes all of Florin's shotgun blasts to bounce onto Ifechi, killing her. He's effectively framed for it. Joins Team Katia later. An all-loving hero who recognizes what's happening to Lucia and tries to help her." },
  { id: "ifechi", label: "Ifechi", book: 3, faction: "CRAWLERS", role: "Medic", x: 950, y: 120,
    desc: "Red Cross medic. Bonds deeply with Florin. They partner through the first four floors. Killed on Floor 4 by Lucia Mar's spell-reflection trap — Florin gets the kill credit. Has an identical sister who appears as a boss elsewhere. Her death sends Florin into a long collapse." },
  { id: "louis", label: "Louis", book: 3, faction: "CRAWLERS", role: "Crawler", x: 950, y: 200,
    desc: "Overweight, balding American. Drove his modified convertible Chevy Astro van into the dungeon when the staircase appeared, earning the Cloud of Exhaust spell (puts mobs to sleep). First meets Royal Court on Floor 5. Becomes Team Katia's ace pilot. Deeply genuine — Juice Box (his eventual love) loves him for having zero pretense. On Floor 8 he kills Sister Ines, triggering the Ysalte crisis. Gets doomed by Ogun." },
  { id: "firas", label: "Firas", book: 3, faction: "CRAWLERS", role: "Crawler", x: 1050, y: 160,
    desc: "Louis's best friend. The two spend the first five floors together. After Floor 5 they get outrageously drunk in a bar, figuring they're done for. Joins Team Katia. Killed in the Floor 6 battle against Queen Imogen by a lightning spell. Louis takes it extremely hard." },
  { id: "gwendolyn", label: "Gwendolyn Duet", book: 3, faction: "CRAWLERS", role: "Crawler", x: 1060, y: 310,
    desc: "Crawler who calls out Ronaldo on the group chat: 'The bomber guy warned all of you dumbasses. Fall back to the train lines. Hold them at the choke points.' Practical, no-nonsense. Part of the wider crawler coalition on Floor 4." },
  { id: "ronaldo", label: "Ronaldo Qu", book: 3, faction: "CRAWLERS", role: "Crawler", x: 1060, y: 400,
    desc: "Crawler involved in the Floor 4 endgame. Argues with Gwendolyn in group chat about whether Carl's warnings were clear enough. No relation to Quan CH." },
  { id: "bautista", label: "Daniel Bautista", book: 3, faction: "CRAWLERS", role: "Crawler", x: 840, y: 180,
    desc: "Crawler. Carl thinks he looks like a Thundercat after his race transformation. Lost his entire family in the Transformation. Donut finds an anklet belonging to Grace Bautista in Book 2 — hinting at a family connection. Develops a romantic relationship with Katia on Floor 6. Part of Team Katia." },
  // ── BOOK 1 ANTAGONISTS ──
  { id: "frank", label: "Frank Q", book: 1, faction: "ANTAGONISTS", role: "Player Killer", x: 340, y: 500,
    desc: "Player killer under Maggie's mind control. Aware of everything but helpless. By Book 3, Maggie is revealed to be blackmailed by a backer who threatens her supposedly-dead family." },
  { id: "maggie", label: "Maggie My", book: 1, faction: "ANTAGONISTS", role: "Player Killer", x: 220, y: 470,
    desc: "Mind-controls Frank as a puppet. Strangles Yvette on live air. In Book 3, revealed to be trapped — a backer threatens her dead family members with transfiguration into killable monsters. She seems exhausted and resigned by her final encounter with Carl." },
  { id: "yvette", label: "Yvette", book: 1, faction: "ANTAGONISTS", role: "Pre-Dungeon", x: 110, y: 510,
    desc: "Frank and Maggie's daughter. Killed by Maggie on live broadcast." },
  { id: "maestro", label: "Prince Maestro", book: 1, faction: "ANTAGONISTS", role: "Host/Boss", x: 480, y: 490,
    desc: "Skull Empire host. Humiliated by Carl on air. Holds a dangerous grudge throughout the series." },
  // ── BOOK 2 ANTAGONISTS ──
  { id: "stalwart", label: "Prince Stalwart", book: 2, faction: "ANTAGONISTS", role: "Antagonist", x: 360, y: 590,
    desc: "Maestro's brother. Orbital strike attempt accidentally kills pop star Manasa instead of Carl and Donut." },
  { id: "miss_quill", label: "Miss Quill", book: 2, faction: "ANTAGONISTS", role: "NPC", x: 600, y: 500,
    desc: "Necromancer secretly running the Over City. Killed by Carl's dynamite trap, triggering the doomsday soul crystal." },
  // ── BOOK 3 ANTAGONISTS ──
  { id: "loita", label: "Loita", book: 3, faction: "ANTAGONISTS", role: "Antagonist", x: 220, y: 580,
    desc: "Devout kua-tin. Replaces Zev as Carl & Donut's PR agent on Floor 4. Openly xenophobic — tells Carl that humans are a cancer and Earth should have simply been destroyed. Insists on adding a self-destruct system to the Robot Donut merchandise toys, over Carl's protests. Carl rigs one to kill her and makes it look like an accident. A Syndicate liaison suspects but can't prove it." },
  // ── SYSTEM / BORANT ──
  { id: "borant", label: "Borant Corp", book: 1, faction: "SYSTEM", role: "Corp Entity", x: 500, y: 670,
    desc: "Alien corporation. Destroyed Earth, runs the dungeon. Secretly bankrupt. Uses its one VETO to negate 83 celestial boxes in Book 2. In Book 3, is clearly desperate — offering Carl a legendary box upgrade in exchange for the source of his Loita-killing knowledge. Carl refuses." },
  { id: "world_ai", label: "World AI", book: 1, faction: "SYSTEM", role: "Admin", x: 350, y: 660,
    desc: "The dungeon's System AI. Assigns guides, manages loot. On Floor 4, awards Carl a fan-sponsored box containing the Dungeon Anarchist's Cookbook. Its subtle interventions suggest an agenda beyond Borant's interests. By Book 6 it is visibly deteriorating and unstable — breaking its own rules, threatening the failsafe, and creeping toward something unprecedented." },
  { id: "zev", label: "Zev", book: 1, faction: "SYSTEM", role: "PR Agent", x: 660, y: 640,
    desc: "Borant's kua-tin PR agent. Sympathetic. Replaced by Loita on Floor 4. On Floor 8, warns Carl that Odette intends to serve as their Faction Wars adjutant and that it could cost Carl his manager. Reports to Cascadia." },
  // ── GALACTIC MEDIA ──
  { id: "odette", label: "Odette", book: 1, faction: "MEDIA", role: "Show Host", x: 130, y: 440,
    desc: "Most famous galactic host. Former crawler (survived to Floor 12, took indentureship). Has complicated history with Mordecai. On Book 6's Floor 8, she reveals she's sponsoring the goddess Nekhebit and announces she is entering the dungeon herself as Nekhebit's vessel. Recommends adjutant candidates to Carl and distracts Harbinger to warn Carl about Huanxin Jinx." },
  { id: "ripper", label: "Ripper Wonton", book: 2, faction: "MEDIA", role: "Show Host", x: 80, y: 360,
    desc: "Alien show host on 'The Danger Zone.' Described as a fuzzy wombat-Ewok hybrid. Carl and Donut appear on his show in Book 2 to deliver inflammatory anti-Skull Empire speech." },
  { id: "manasa", label: "Manasa", book: 2, faction: "MEDIA", role: "Pre-Dungeon", x: 80, y: 530,
    desc: "Famous galactic pop star. Her production trailer accidentally destroyed by Prince Stalwart's orbital strike." },
  { id: "mexx", label: "Mexx-6000", book: 3, faction: "MEDIA", role: "Admin", x: 130, y: 310,
    desc: "A Syndicate AI or technical liaison. Meets with Carl in the production trailer on Floor 4 to explain why his crawler powers work in that space. When Carl can't follow the explanation, she offers to translate into 'earth monkey speak.' Represents the Syndicate's production infrastructure." },
  // ── BOOK 2 DUNGEON NPCs ──
  { id: "signet", label: "Tsarina Signet", book: 2, faction: "NPCS", role: "Elite NPC", x: 360, y: 380,
    desc: "Half Naiad/Elf Elite NPC. Stars in 'Vengeance of the Daughter.' Kidnaps Donut to coerce Carl. Carl outmaneuvers her via the show's producers. In Book 3, she becomes aware of her own NPC status and ultimately sacrifices herself on Floor 5 to break Diwata's peace seal, enabling the crawlers to fight." },
  { id: "grimaldi", label: "Grimaldi", book: 2, faction: "NPCS", role: "Boss", x: 250, y: 410,
    desc: "Pestiferous Fae turned parasitic vine circus ringmaster. Loves Signet. Carl negotiates with producers to resolve the quest by poisoning himself to commune with him." },
  { id: "featherfall", label: "Magistrate Featherfall", book: 2, faction: "NPCS", role: "NPC", x: 740, y: 490,
    desc: "Nominal ruler of the Over City. Revealed to have been dead the whole time — mummified in his office while Miss Quill ran the city. Carl is declared the new Magistrate after Quill's death." },
  { id: "gumgum", label: "GumGum", book: 2, faction: "NPCS", role: "NPC", x: 660, y: 440,
    desc: "Skyfowl NPC. Approaches Carl and Donut in the Desperado Club, triggering the murder-mystery quest. Found dead with a guard pass and a blood-covered necromancy letter." },
  { id: "heather", label: "Heather the Bear", book: 2, faction: "NPCS", role: "Boss", x: 150, y: 360,
    desc: "Haunted, parasite-infested bear from Grimaldi's circus. Carl mercy-kills her — burning the parasites away first — enabling Signet to complete her spell." },
  { id: "samantha", label: "Samantha", book: 4, faction: "NPCS", role: "Deity", x: 240, y: 650,
    desc: "Withering Spirit Psamathe — banished minor deity of unrequited love. Inhabits a decapitated latex sex doll head found in Carl's inventory. Vulgar, loud, and shockingly perceptive. Her daughter Mrs. Ghazi is a sand ooze Floor 5 Borough Boss. Joins Royal Court on Floor 5 after Carl pokes her teeth. On Floor 8, Ysalte recognizes her as Psamathe and attacks. She intercepts and taunts Ysalte, taking the god's blow without flinching." },
  // ── BOOK 3 NPCs (continued) ──
  { id: "chaco", label: "Chaco the Bard", book: 3, faction: "NPCS", role: "Show Host", x: 550, y: 670,
    desc: "Former crawler from Mordecai's season. Now hosts The Prize Carousel dungeon minigame — winged, wolf-headed man in a checkered leisure suit. Killed Mordecai's brother Uzzi on Odette's instruction to get the floor key before the timer ran out. Mordecai attacks him on sight in Book 3 (earning a 7-day safe-room time-out). Deeply remorseful but bound to silence. His warning to Carl: 'They always make you turn on your party.'" },
  // ── BOOK 4 NEW NODES ──
  { id: "juice_box", label: "Juice Box", book: 4, faction: "NPCS", role: "NPC", x: 120, y: 700,
    desc: "Changeling NPC prostitute at Hump Town's inn on Floor 5. Henrik's sister. Deeply loyal to her changeling family. Becomes a critical ally to Carl and the Royal Court — helps save Hump Town from bombardment. Later goes to Floor 9 as an aquatic form to rally NPC factions. Eventually co-warlord of the NPC faction. Gets engaged to Louis." },
  { id: "henrik", label: "Henrik", book: 4, faction: "NPCS", role: "NPC", x: 50, y: 700,
    desc: "Changeling and Juice Box's brother. Holds one of the three pocket-watch pieces of the Gate of the Feral Gods artifact. Carl must retrieve his piece to assemble the Gate." },
  { id: "mrs_ghazi", label: "Mrs. Ghazi", book: 4, faction: "NPCS", role: "Boss", x: 360, y: 750,
    desc: "Samantha's daughter and a sand ooze Floor 5 Borough Boss (Level 52). Created by Samantha's union with King Blaine. Devoted protector. Samantha believes she was killed in the bubble's acid, which causes Samantha to offer her daughter's organs to save Louis — but Mrs. Ghazi likely survived to Floor 9." },
  // Book 4 deities
  { id: "orthrus", label: "Orthrus", book: 4, faction: "SYSTEM", role: "Deity", x: 420, y: 750,
    desc: "A feral god who turns out to be a massive puppy — not the terrifying beast everyone feared. Summoned when Carl and Katia are forced to use the Gate of the Feral Gods to escape the ocean floor. Gentle and confused rather than malevolent. Carl bonds with him and works to keep him safe from his enraged divine father Emberus." },
  { id: "emberus", label: "Emberus", book: 4, faction: "ANTAGONISTS", role: "Deity", x: 120, y: 580,
    desc: "Angry and cruel god. Father of Orthrus's deceased owner. Arrives on Floor 5 to reclaim Orthrus after Carl summons him via the Gate, threatening thousands of crawlers. Carl uses Donut's Meathook scroll to lure Orthrus to Emberus, resolving the crisis — but Samantha may have been involved in killing Geyrun, which complicates things with him." },
  { id: "algos", label: "Algos", book: 4, faction: "ANTAGONISTS", role: "Deity", x: 60, y: 490,
    desc: "Ancient god of pain. Maggie My (possessing Chris) attempts to summon Algos using a Celestial Grenade during a Floor 5 confrontation. Katia petrifies the possessed Chris and Donut drops him into the Subterranean quadrant to prevent the summoning." },
  { id: "denise", label: "Denise", book: 4, faction: "ANTAGONISTS", role: "Boss", x: 120, y: 490,
    desc: "Feral goose goddess — Air castle boss on Floor 5. Completely immune to direct attacks. Carl defeats her by jamming her into the kitchen sink's garbage disposal grinder, since she is immune to attacks but not to the environment." },
  { id: "commandant_kane", label: "Commandant Kane", book: 4, faction: "ANTAGONISTS", role: "Boss", x: 50, y: 590,
    desc: "Holds one of the three Gate of the Feral Gods pocket-watch pieces. Carl must defeat or retrieve the piece from him to assemble the complete artifact." },
  // ── BOOK 3 DUNGEON NPCs ──
  { id: "growler_gary", label: "Growler Gary", book: 3, faction: "NPCS", role: "NPC", x: 430, y: 670,
    desc: "Gnoll bartender at a Floor 4 safe room called The Downward Dog. Refers to himself exclusively in third person ('Growler Gary thinks...') — except in very serious moments when he says 'I,' which signals the conversation has become genuinely grave." },
  // ── BOOK 4 NEW CRAWLERS ──
  { id: "tserendolgor", label: "Tserendolgor (Ren)", book: 4, faction: "CRAWLERS", role: "Crawler", x: 1160, y: 270,
    desc: "Mongolian former runway model turned flamethrower-wielding Dog Soldier. Race: Dog Soldier. Class: Crisper. Wields an enchanted flamethrower named 'Velma.' Enters the dungeon to rescue friends and family. Donut constantly harasses her over her dog-themed race. Allied with Meadow Lark on Floor 4. On Floor 5, Emberus mistakes her bubble for Orthrus — he pounds on the wall screaming while her entire world melts. Survives. Dies on Floor 8, donating her gear and pet Garret (a Tummy Acher) to Carl. Her sacrifice becomes a symbol: 'You're more than just a person. You're our hope.'" },
  // ── BOOK 4 SYSTEM/SYNDICATE ──
  { id: "orren", label: "Orren", book: 4, faction: "SYSTEM", role: "Admin", x: 600, y: 720,
    desc: "Syndicate Liaison — a Gondii parasitic worm inhabiting a fishbowl of liquid mounted on a mechanical body. Carl's 'vice principal.' First appears investigating Loita's death on Floor 5, constructing an elaborate (mostly accurate) picture of Carl's guilt. Manages negotiations between Borant, the System AI, and crawlers. Negotiates the Gate of the Feral Gods handover deal. Morally complicated — liaisons are required to be independent of their race, and Orren takes it seriously." },
  { id: "quasar", label: "Quasar", book: 4, faction: "SYSTEM", role: "Admin", x: 700, y: 720,
    desc: "Carl's Nullian lawyer — looks like a stereotypical Area 51 alien (gray, large eyes, bulbous head) in a tan suit with a hula girl tie. Nullians are rare in Syndicate space. Immediately annoying to Orren. Negotiates Carl's deal with Orren for the Gate of the Feral Gods, securing mercenary bodyguards and the Zerzura spell in exchange. Informs Carl that crawlers become full Syndicate citizens at Floor 10." },
  // ── BOOK 4 NPC BODYGUARDS (Desperado Club) ──
  { id: "sledge", label: "The Sledge", book: 4, faction: "NPCS", role: "NPC", x: 310, y: 730,
    desc: "7-foot Cretin bodyguard in a tuxedo at the Desperado Club. Donut's personal favorite. Close friends with Bomo. Hired as permanent Royal Court security after failing to stop an assassination attempt on Donut (Carl requested them instead of retribution). Buys a magic protection spell with his own money specifically to protect Donut. On Floor 6, crashes a Twister into a turret and teleports Queen Imogen's entire castle to Floor 9 using the Zerzura spell. Last words: 'No let Bomo beat my Frogger score.'" },
  { id: "bomo", label: "Bomo", book: 4, faction: "NPCS", role: "NPC", x: 200, y: 730,
    desc: "Cretin bodyguard at the Desperado Club, close friends with Sledge. Hired alongside Sledge as permanent Royal Court security. Both become mercenary bodyguards as part of the Gate of the Feral Gods exchange deal with Orren. Assigned as Bomo throughout the crawl." },
  { id: "very_sullen", label: "Very Sullen", book: 4, faction: "NPCS", role: "NPC", x: 110, y: 730,
    desc: "Third Cretin bodyguard from the Desperado Club. Thinner face than the others, tiny emotionless dot eyes. Rarely speaks. Hired specifically to guard Katia on Floor 5, then becomes her full-time mercenary bodyguard from Floor 6 onward. Part of the Gate deal with Orren." },
  { id: "clay_ton", label: "Clay-ton", book: 3, faction: "NPCS", role: "NPC", x: 440, y: 730,
    desc: "Fourth Cretin bodyguard from the Desperado Club. First hired as personal security for Elle McGibbons (due to her leaderboard status) on Floor 4. Becomes a mercenary bodyguard as part of the Gate deal. On Floor 6 assigned by Carl to protect Chris Andrews." },
  // ── BOOK 4 DEITIES ──
  { id: "hellik", label: "Hellik", book: 4, faction: "SYSTEM", role: "Deity", x: 520, y: 750,
    desc: "God of Sun and Life. Twin brother of Emberus. Named in Floor 5 quests as the prime suspect in Geyrun's murder — though he was in divine council when it happened. Emberus tasks Carl with killing him (with smite if Carl reaches Floor 18 without completing it). Later reveals himself to Carl as unexpectedly friendly, denies the murder, and asks Carl to convince Emberus to ally against Nekhebit." },
  { id: "geyrun", label: "Geyrun", book: 4, faction: "BACKSTORY", role: "Pre-Dungeon", x: 1160, y: 200,
    desc: "Emberus's deceased favorite son and original owner of Orthrus the puppy. Murdered by an unknown assailant before the story begins — Emberus blinded himself in grief. His death sets off the entire Floor 5 divine crisis: Emberus comes for Orthrus, tasks Carl with the 'Find Out Who Killed My Son' and 'Kill Hellik' quests, and the murder mystery runs through subsequent books." },
  // ── BACKSTORY ──
  { id: "beatrice", label: "Beatrice", book: 1, faction: "BACKSTORY", role: "Pre-Dungeon", x: 110, y: 200,
    desc: "Carl's ex-girlfriend, Donut's original owner. Presumed dead. Her absence shapes Carl's fierce protectiveness toward Donut. Later revealed to be alive — rescued by Odette, who blackmailed Borant over her; being transported to the inner system." },

  // ══════════════════════════════════════════════════════════════════════════
  // ── BOOK 5: THE BUTCHER'S MASQUERADE (Floor 6 – The Hunting Grounds) ──
  // ══════════════════════════════════════════════════════════════════════════
  { id: "vrah", label: "Vrah", book: 5, faction: "ANTAGONISTS", role: "Hunter", x: 1200, y: 500,
    desc: "Mantis hunter and veteran dungeon huntress. Mayor of Zockau on Floor 6. Decapitates kills and wears their heads; death count in the thousands. Starts a vendetta against Carl after he kills her sister Xindy. Stabbed by Carl with the Arrow of Enthusiastic Double Gonorrhea. Savaged to death by Mongo and Kiwi at the Butcher's Masquerade." },
  { id: "xindy", label: "Xindy", book: 5, faction: "ANTAGONISTS", role: "Hunter", x: 1300, y: 450,
    desc: "Vrah's younger sister. Dark Hive mantis hunter. Killed early in Floor 6 when Carl's party raids Zockau, triggering Vrah's furious vendetta." },
  { id: "circe_took", label: "Circe Took", book: 5, faction: "ANTAGONISTS", role: "Hunter Leader", x: 1300, y: 600,
    desc: "Minor mantis hive queen, mother of Vrah and Xindy. Panel moderator at CrawlCon. Enraged by Xindy's death; sponsors goddess Diwata to cure Vrah of the Arrow of Enthusiastic Double Gonorrhea. Uses influence to let hunters leave early after Borant loses control." },
  { id: "diwata", label: "Diwata", book: 5, faction: "ANTAGONISTS", role: "Deity", x: 1200, y: 650,
    desc: "Minor goddess sponsored by Circe Took onto Floor 6 to cure Vrah. Becomes a major threat at the Butcher's Masquerade. Killed by Donut's Laundry Day spell during the final battle." },
  { id: "queen_imogen", label: "Queen Imogen", book: 5, faction: "ANTAGONISTS", role: "Country Boss", x: 1100, y: 580,
    desc: "Level 145 high elf Fallen Cleric/Sorceress, Country Boss of Floor 6. Hosts the Butcher's Masquerade. Xenophobic queen who helped kill Signet's mother and tried to eradicate King Finian's half-blood children. Immune to poison and curse; susceptible to blunt force. Killed by Signet at the Masquerade — at the cost of Signet's own life." },
  { id: "ferdinand", label: "Ferdinand (Gravy Boat)", book: 5, faction: "NPCS", role: "Boss/Pet", x: 1100, y: 460,
    desc: "Yellow tomcat (real name Gravy Boat), Donut's unrequited pre-dungeon love interest, owned by neighbor Marjory Williams. Abducted and transformed into Level 100 Province Boss and Queen Imogen's familiar. Wields turban with lightning spell and phase-jump. Transported to Floor 9 with the castle; becomes co-Warlord of the NPC Home Team faction alongside Juice Box." },
  { id: "kiwi", label: "Kiwi", book: 5, faction: "NPCS", role: "Pet/Ally", x: 280, y: 50,
    desc: "Female mongoliensis dinosaur, Big Tina's mother. Originally a bear, transformed long ago by Scolopendra's attack. Mongo's romantic partner (to Donut's horror). Charmed by Apothecary's potion into becoming Donut's minion. Helps Mongo kill Vrah at the Masquerade. Transported to Floor 9 as part of the Princess Posse army." },
  { id: "big_tina", label: "Big Tina", book: 5, faction: "NPCS", role: "Pet/Ally", x: 160, y: 50,
    desc: "Giant allosaurus ballerina on Floor 6, Kiwi's daughter. Both were originally bears transformed long ago by Scolopendra. Sought by Carl's party as a quest target. Transported to Floor 9 as part of the Princess Posse army." },
  { id: "eva", label: "Eva Sigrid", book: 2, faction: "CRAWLERS", role: "Player Killer", x: 830, y: 50,
    desc: "Icelandic economics professor, Katia's former friend. Hekla's right-hand enforcer — her anger issues weaponized by her own therapist. Four-armed cobra-head race; 13+ Player Killer skulls. Abandons Katia in Book 2 during Floor 3 race selection. Central antagonist of Katia's arc in Book 5. Final act: places the Crown of the Sepsis Whore on Katia as she dies, binding Katia (or Donut) to the 9th floor." },
  { id: "gideon", label: "Gideon", book: 5, faction: "CRAWLERS", role: "Crawler", x: 1160, y: 130,
    desc: "Crawler who allies with Carl on Floors 5 and 6. Leads a team outside the elf castle during the Masquerade battle. Killed in the fighting — his death weighs on Carl, who recruited him." },
  { id: "britney", label: "Britney", book: 5, faction: "CRAWLERS", role: "Crawler", x: 1160, y: 60,
    desc: "Ukrainian plastic surgery patient turned crawler. Wears a fur bikini, carries a spiked stick, has an extinction sigil tattoo. Acts as Donut's guitarist at the Masquerade talent show with spectacular playing. Face badly scarred in the final battle. On Floor 8 she is in Katia's squad alongside Tran, Bautista, and Louis." },

  // ══════════════════════════════════════════════════════════════════════════
  // ── BOOK 6: THE EYE OF THE BEDLAM BRIDE (Floor 8 – The Ghosts of Earth) ──
  // ══════════════════════════════════════════════════════════════════════════

  // New NPCs / system characters
  { id: "cascadia", label: "Cascadia", book: 6, faction: "SYSTEM", role: "Admin", x: 460, y: 760,
    desc: "Lead engineer and current executive producer of Dungeon Crawler World: Earth. A kua-tin; small with long droopy catfish whiskers and dull scales. Makes the overly enthusiastic daily announcements. Recently divorced. By Book 6 she is dangerously close to a breakdown, warns crawlers she is 'one crisis shy of pulling the failsafe, which would kill us all.' Briefly removes protections and dares Carl to attack her at a warlord meeting." },
  { id: "baroness_victory", label: "Baroness Victory", book: 6, faction: "SYSTEM", role: "Admin", x: 800, y: 760,
    desc: "Skull Empire attorney-judge chosen as Carl and Donut's Faction Wars adjutant. Half-sister of Queen Consort Ugloo. A fan of legal loopholes — once put her own aunt in indentureship for unpaid taxes. Selected by Carl over Odette's other options (Ripper Wonton, Drick) on the advice of Quasar. Provides rule access and political leverage for the Princess Posse." },
  { id: "harbinger", label: "Harbinger", book: 6, faction: "SYSTEM", role: "Admin", x: 900, y: 760,
    desc: "Caprid liaison working behind the scenes. Fundamentally opposes Carl and Prepotente's continued presence in the crawl and is 'actively working' to remove them. Supervises Carl and Donut's Floor 8 TV appearance on Shadow Boxer. Odette distracts him by shooting down an unmanned liaison ship; he disappears and the World AI threatens to 'pull his intestines out through his hair follicles' if he attempts to harm the crawlers outside the game." },

  // New crawlers B6
  { id: "sister_ines", label: "Sister Ines", book: 6, faction: "CRAWLERS", role: "Crawler", x: 1200, y: 370,
    desc: "Former nun turned crawler from a Cuban prison courtyard. Cat-girl race (Havana Brown). Calm, authoritative, and subtly coercive — her race carries a charm-like influence. History of violent 'sin-purging'; poisoned her entire convent before incarceration. Paz and Anton were her prison guards, not counselees. Becomes completely unmoored after she traps Paz in a card to prevent him from leaving. Increasingly convinced the dungeon is divine punishment and she must 'save' everyone. Killed by Louis, triggering the goddess Ysalte." },
  { id: "paz_lo", label: "Paz Lo", book: 6, faction: "CRAWLERS", role: "Crawler", x: 1300, y: 370,
    desc: "Santero tank, cousin of Anton. Enters Floor 8 with Sister Ines and Anton. Wears medieval armor and a backwards baseball cap. Has a self-destruct directional blast and a turtle shield ability. When Ogun manifests and kills Anton for resurrecting Yemaya, Paz is permanently doomed. To prevent him from dying and 'abandoning' her, Sister Ines traps him as a T'Ghee Card. Freed from the card at the climax, he kills the goddess Ysalte, saving everyone on the floor." },
  { id: "anton", label: "Anton Lopez", book: 6, faction: "CRAWLERS", role: "Crawler", x: 1400, y: 370,
    desc: "Paz's cousin and prison guard. Enters Floor 8 with Sister Ines and Paz. Killed by the god Ogun as divine punishment after the party resurrects Yemaya against Ogun's wishes. His death triggers the permanent doom on Paz and sets off the fatal spiral of Sister Ines's madness." },
  { id: "tran", label: "Tran", book: 5, faction: "CRAWLERS", role: "Crawler", x: 1060, y: 490,
    desc: "Crawler with a metal-detecting ability and pathfinding skill. Lost his legs in the Cage Fight at the end of Floor 6. Received a magical floating disc to carry him. On Floor 8 he is in Katia's squad alongside Bautista, Britney, and Louis. His wheelchair is destroyed in the fight with Amayon and Ysalte." },
  { id: "osvaldo", label: "Osvaldo", book: 5, faction: "CRAWLERS", role: "Crawler", x: 1060, y: 560,
    desc: "Brazilian crawler, member of team Flamengo. Chose Curupira race / Ranger class and stacked all points into Dexterity. Pet Stone Hawk named Gimli (eaten by Bianca on Floor 6). Survives the Masquerade and descends before Carl's Faction Wars announcement. On Floor 8 appears on the leaderboard for the first time." },

  // New NPCs/bosses B6
  { id: "shi_maria", label: "Shi Maria", book: 6, faction: "NPCS", role: "Boss/Deity", x: 1350, y: 600,
    desc: "Level 140 City Boss demi-god, also known as the Bedlam Bride, the Widow Endless, and MaeMae. Located in the Bahamas region of Floor 8. Woman's head on a giant spider body. Reaper Spider minion. Inflicts Permanent Insanity and Permanent Blindness. Was once married to a god, now missing. Intelligent and manipulative. Nominally captured by Carl's party as a T'Ghee Card, but the relationship is mutual: she merges with Carl at the climax, tattooing her third eye on his chest. Now bound to Carl's tattoo — he can open the Eye to use her power, at dangerous cost." },
  { id: "amayon", label: "Amayon", book: 6, faction: "NPCS", role: "Boss/Deity", x: 1400, y: 500,
    desc: "Prince of Sheol (demon realm), cast out by a brother's betrayal and banished to Floor 8. In his true form an enormous centaur with a demonic deer head and lava-red bubbling skin — chest at the height of a 32-story building. Enslaved by Ysalte. Carl organizes a world quest to free him before the floor collapses. Afterward, Amayon thanks Carl and departs for the 15th floor to wage war on his three brothers." },
  { id: "ysalte", label: "Ysalte", book: 6, faction: "ANTAGONISTS", role: "Deity", x: 1300, y: 500,
    desc: "Level 250 goddess of Hopelessness and Insanity. Patron of Sister Ines. Manifests from Ines's dissolving corpse when Louis kills her. Invulnerable on the floor. Curses all of Carl's potions into vinegar. Enslaves Amayon. The dungeon converts the resulting crisis into a final card battle. Killed by Paz Lo when he is freed from his card, saving everyone on the floor." },
  { id: "heyzoos", label: "HeyZoos (Uzi Jesus)", book: 6, faction: "NPCS", role: "Boss/Deity", x: 1350, y: 440,
    desc: "Unique undead T'Ghee Card from Ecuador. Level 140 ranged healer totem. Catchphrase: 'I am the way, motherfucker.' Can resurrect other totems and turn blood into lead. One of Carl's most memorable card captures." },
];

export const EDGES = [
  // Core party
  { from: "carl", to: "donut", type: "party", label: "partners with" },
  { from: "mordecai", to: "carl", type: "trains", label: "trains/guides" },
  { from: "mordecai", to: "donut", type: "trains", label: "manages" },
  { from: "donut", to: "mongo", type: "companion", label: "tames" },
  { from: "beatrice", to: "donut", type: "exgf", label: "original owner" },
  { from: "beatrice", to: "carl", type: "exgf", label: "ex-girlfriend" },
  { from: "katia", to: "carl", type: "joined", label: "joins party" },
  { from: "katia", to: "donut", type: "joined", label: "joins party" },
  { from: "hekla", to: "carl", type: "brokers", label: "asks to adopt Katia" },
  { from: "hekla", to: "katia", type: "connected", label: "former party leader" },
  // Meadow Lark
  { from: "carl", to: "brandon", type: "allied", label: "allies with" },
  { from: "carl", to: "imani", type: "allied", label: "allies with" },
  { from: "carl", to: "agatha", type: "allied", label: "allies with" },
  { from: "brandon", to: "elle", type: "protected", label: "protects" },
  { from: "brandon", to: "jack", type: "leads", label: "leads group" },
  { from: "imani", to: "brandon", type: "allied", label: "works alongside" },
  { from: "chris", to: "brandon", type: "allied", label: "brother/partner" },
  { from: "yolanda", to: "jack", type: "causes", label: "tries to stop" },
  { from: "jack", to: "yolanda", type: "causes", label: "triggers elemental → kills" },
  // Other crawlers B1
  { from: "carl", to: "li_jun", type: "rescued", label: "rescues on show" },
  { from: "carl", to: "li_na", type: "rescued", label: "rescues on show" },
  { from: "carl", to: "zhang", type: "rescued", label: "rescues on show" },
  // Antagonists B1
  { from: "maggie", to: "frank", type: "puppet", label: "mind-controls" },
  { from: "frank", to: "carl", type: "hunts", label: "attacks" },
  { from: "maggie", to: "carl", type: "antagonizes", label: "antagonizes" },
  { from: "carl", to: "frank", type: "causes", label: "dynamite trap" },
  { from: "maggie", to: "yvette", type: "killed", label: "strangles on air" },
  { from: "carl", to: "maestro", type: "antagonizes", label: "humiliates on air" },
  { from: "maestro", to: "carl", type: "antagonizes", label: "political grudge" },
  { from: "maestro", to: "li_jun", type: "antagonizes", label: "traps on show" },
  // Antagonists B2
  { from: "carl", to: "stalwart", type: "antagonizes", label: "provokes speech" },
  { from: "stalwart", to: "carl", type: "antagonizes", label: "orbital strike attempt" },
  { from: "stalwart", to: "manasa", type: "killed", label: "accidentally destroys trailer" },
  { from: "stalwart", to: "maestro", type: "connected", label: "brother" },
  { from: "carl", to: "miss_quill", type: "killed", label: "dynamite kills" },
  { from: "miss_quill", to: "featherfall", type: "connected", label: "ruled in his name" },
  { from: "miss_quill", to: "gumgum", type: "killed", label: "implicated in death" },
  // Antagonists B3
  { from: "loita", to: "zev", type: "replaces", label: "replaces as PR agent" },
  { from: "loita", to: "carl", type: "antagonizes", label: "racist hostility" },
  { from: "loita", to: "donut", type: "antagonizes", label: "racist hostility" },
  { from: "carl", to: "loita", type: "killed", label: "robot donut booby trap" },
  { from: "borant", to: "loita", type: "employs", label: "employs" },
  // NPCs B2
  { from: "signet", to: "carl", type: "coerces", label: "kidnaps Donut / coerces" },
  { from: "signet", to: "grimaldi", type: "loved", label: "loves" },
  { from: "carl", to: "signet", type: "quest", label: "resolves quest" },
  { from: "carl", to: "grimaldi", type: "quest", label: "poisons self to negotiate" },
  { from: "carl", to: "heather", type: "killed", label: "mercy kill" },
  { from: "signet", to: "heather", type: "coerces", label: "demands sacrifice" },
  { from: "gumgum", to: "carl", type: "quest", label: "triggers murder quest" },
  { from: "carl", to: "featherfall", type: "connected", label: "declared new Magistrate" },
  // NPCs B3
  { from: "carl", to: "growler_gary", type: "allied", label: "frequents bar" },
  { from: "mexx", to: "carl", type: "connected", label: "explains production trailer rules" },
  // System
  { from: "borant", to: "world_ai", type: "controls", label: "runs" },
  { from: "borant", to: "zev", type: "employs", label: "employs" },
  { from: "borant", to: "maestro", type: "connected", label: "Skull Empire deal" },
  { from: "zev", to: "carl", type: "manages", label: "PR manages" },
  { from: "zev", to: "donut", type: "manages", label: "bonds with" },
  { from: "world_ai", to: "carl", type: "connected", label: "cryptic messages / Cookbook" },
  { from: "world_ai", to: "mordecai", type: "connected", label: "assigned guide" },
  // Media
  { from: "odette", to: "carl", type: "hosts", label: "interviews/warns" },
  { from: "odette", to: "donut", type: "hosts", label: "secret advice" },
  { from: "mordecai", to: "odette", type: "connected", label: "prior history" },
  { from: "ripper", to: "carl", type: "hosts", label: "hosts on Danger Zone" },
  { from: "borant", to: "ripper", type: "employs", label: "employs" },
  { from: "borant", to: "mexx", type: "employs", label: "employs/deploys" },
  { from: "odette", to: "chris", type: "connected", label: "tries to warn Carl (muted)" },
  // B3 crawler relations
  { from: "miriam", to: "prepotente", type: "companion", label: "shepherd/mother figure" },
  { from: "prepotente", to: "miriam", type: "companion", label: "companion/ward" },
  { from: "carl", to: "miriam", type: "allied", label: "meets/allies with" },
  { from: "carl", to: "prepotente", type: "connected", label: "frenemy relationship" },
  { from: "florin", to: "ifechi", type: "allied", label: "partners with" },
  { from: "lucia", to: "ifechi", type: "killed", label: "spell-reflection trap" },
  { from: "lucia", to: "florin", type: "tricks", label: "frames for Ifechi's death" },
  { from: "florin", to: "katia", type: "allied", label: "joins Team Katia" },
  { from: "louis", to: "firas", type: "allied", label: "best friends" },
  { from: "louis", to: "katia", type: "allied", label: "joins Team Katia" },
  { from: "firas", to: "katia", type: "allied", label: "joins Team Katia" },
  { from: "bautista", to: "katia", type: "allied", label: "romantic relationship" },
  { from: "quan", to: "carl", type: "antagonizes", label: "interferes with Floor 4 endgame" },
  { from: "carl", to: "quan", type: "causes", label: "cuts off arm to stop him" },
  { from: "lucia", to: "carl", type: "antagonizes", label: "marks Carl & Donut" },
  { from: "hekla", to: "katia", type: "mentors", label: "true agenda (covert)" },
  { from: "gwendolyn", to: "ronaldo", type: "connected", label: "argue in crawler chat" },
  // Book 4 edges
  { from: "tserendolgor", to: "carl", type: "allied", label: "ally / symbol of hope" },
  { from: "tserendolgor", to: "imani", type: "allied", label: "Meadow Lark ally" },
  { from: "emberus", to: "tserendolgor", type: "antagonizes", label: "mistakes for Orthrus" },
  { from: "orren", to: "carl", type: "controls", label: "investigates / regulates" },
  { from: "quasar", to: "carl", type: "allied", label: "Carl's lawyer" },
  { from: "quasar", to: "orren", type: "antagonizes", label: "legal adversary" },
  { from: "orren", to: "borant", type: "employs", label: "Syndicate liaison" },
  { from: "sledge", to: "donut", type: "protected", label: "dedicated bodyguard" },
  { from: "sledge", to: "bomo", type: "allied", label: "close friends" },
  { from: "bomo", to: "carl", type: "protected", label: "Royal Court security" },
  { from: "very_sullen", to: "katia", type: "protected", label: "permanent bodyguard" },
  { from: "clay_ton", to: "elle", type: "protected", label: "hired by Elle" },
  { from: "clay_ton", to: "chris", type: "protected", label: "assigned by Carl" },
  { from: "hellik", to: "emberus", type: "antagonizes", label: "suspected of killing Geyrun" },
  { from: "geyrun", to: "orthrus", type: "companion", label: "original owner" },
  { from: "emberus", to: "geyrun", type: "companion", label: "beloved son (deceased)" },
  { from: "chaco", to: "mordecai", type: "antagonizes", label: "killed Mordecai's brother Uzzi" },
  { from: "odette", to: "chaco", type: "controls", label: "instructed to kill Uzzi" },
  { from: "carl", to: "samantha", type: "companion", label: "wakes / reluctant allies" },
  { from: "samantha", to: "carl", type: "companion", label: "joins Royal Court" },
  { from: "samantha", to: "mrs_ghazi", type: "companion", label: "mother/daughter" },
  { from: "juice_box", to: "henrik", type: "allied", label: "siblings" },
  { from: "juice_box", to: "louis", type: "allied", label: "engaged to" },
  { from: "carl", to: "juice_box", type: "allied", label: "saves Hump Town / allies" },
  { from: "juice_box", to: "carl", type: "allied", label: "key NPC ally" },
  { from: "carl", to: "henrik", type: "quest", label: "retrieves Gate piece from" },
  { from: "carl", to: "commandant_kane", type: "quest", label: "retrieves Gate piece from" },
  { from: "carl", to: "orthrus", type: "companion", label: "summons / protects" },
  { from: "emberus", to: "orthrus", type: "companion", label: "pursues / father figure" },
  { from: "emberus", to: "carl", type: "antagonizes", label: "threatens crawlers" },
  { from: "maggie", to: "algos", type: "quest", label: "attempts to summon" },
  { from: "maggie", to: "chris", type: "puppet", label: "infiltrator possession" },
  { from: "carl", to: "denise", type: "killed", label: "garbage disposal kill" },
  { from: "carl", to: "maggie", type: "killed", label: "kills with Mordecai's potion" },
  { from: "katia", to: "maggie", type: "allied", label: "petrifies possessed Chris" },
  { from: "samantha", to: "emberus", type: "connected", label: "involved in Geyrun's death" },

  // Book 5 edges
  { from: "carl", to: "xindy", type: "killed", label: "kills (triggers Vrah vendetta)" },
  { from: "vrah", to: "xindy", type: "companion", label: "sisters" },
  { from: "circe_took", to: "vrah", type: "companion", label: "mother" },
  { from: "circe_took", to: "xindy", type: "companion", label: "mother" },
  { from: "circe_took", to: "diwata", type: "allied", label: "sponsors" },
  { from: "vrah", to: "carl", type: "hunts", label: "prime hunting target" },
  { from: "vrah", to: "queen_imogen", type: "allied", label: "uses to inconvenience Carl" },
  { from: "mongo", to: "vrah", type: "killed", label: "kills with Kiwi" },
  { from: "kiwi", to: "vrah", type: "killed", label: "kills with Mongo" },
  { from: "donut", to: "diwata", type: "killed", label: "Laundry Day spell" },
  { from: "queen_imogen", to: "signet", type: "antagonizes", label: "killed Signet's mother" },
  { from: "signet", to: "queen_imogen", type: "killed", label: "assassinates (sacrifices self)" },
  { from: "queen_imogen", to: "ferdinand", type: "companion", label: "familiar/pet" },
  { from: "ferdinand", to: "donut", type: "connected", label: "unrequited love interest" },
  { from: "donut", to: "ferdinand", type: "connected", label: "pre-dungeon fixation" },
  { from: "sledge", to: "ferdinand", type: "allied", label: "teleports castle to Floor 9" },
  { from: "ferdinand", to: "juice_box", type: "allied", label: "co-Warlords Floor 9" },
  { from: "mongo", to: "kiwi", type: "companion", label: "romantic partner" },
  { from: "kiwi", to: "big_tina", type: "companion", label: "mother" },
  { from: "donut", to: "kiwi", type: "companion", label: "charmed as minion" },
  { from: "hekla", to: "eva", type: "controls", label: "turned patient into enforcer" },
  { from: "eva", to: "katia", type: "antagonizes", label: "player-kills, taunts, betrays" },
  { from: "katia", to: "eva", type: "killed", label: "hunts down and kills" },
  { from: "gideon", to: "carl", type: "allied", label: "recruited by Carl" },
  { from: "britney", to: "donut", type: "allied", label: "Masquerade guitarist" },
  { from: "tran", to: "katia", type: "allied", label: "Floor 5–6 ally" },

  // Book 6 edges
  // Cascadia / system
  { from: "borant", to: "cascadia", type: "employs", label: "employs / exec producer" },
  { from: "cascadia", to: "zev", type: "employs", label: "Zev reports to Cascadia" },
  { from: "cascadia", to: "world_ai", type: "connected", label: "executive over deteriorating AI" },
  { from: "cascadia", to: "carl", type: "antagonizes", label: "removes protections / dares attack" },
  // Adjutant
  { from: "odette", to: "baroness_victory", type: "brokers", label: "recommends as adjutant" },
  { from: "baroness_victory", to: "carl", type: "allied", label: "Faction Wars adjutant" },
  { from: "odette", to: "carl", type: "allied", label: "enters dungeon as Nekhebit's vessel" },
  // Harbinger
  { from: "harbinger", to: "carl", type: "antagonizes", label: "works to remove from crawl" },
  { from: "world_ai", to: "harbinger", type: "antagonizes", label: "threatens if he harms crawlers" },
  // Sister Ines / Paz / Anton cluster
  { from: "sister_ines", to: "paz_lo", type: "controls", label: "traps as card to prevent leaving" },
  { from: "sister_ines", to: "anton", type: "companion", label: "prison group" },
  { from: "paz_lo", to: "anton", type: "companion", label: "cousins" },
  { from: "sister_ines", to: "carl", type: "antagonizes", label: "three-way card battle / keys" },
  { from: "carl", to: "sister_ines", type: "antagonizes", label: "cannot trust / conflict" },
  { from: "louis", to: "sister_ines", type: "killed", label: "kills, triggering Ysalte" },
  { from: "paz_lo", to: "ysalte", type: "killed", label: "freed from card, kills goddess" },
  { from: "quan", to: "sister_ines", type: "antagonizes", label: "three-way card battle" },
  { from: "donut", to: "quan", type: "killed", label: "kills after card battle" },
  // Ysalte / Amayon
  { from: "ysalte", to: "sister_ines", type: "controls", label: "patron goddess" },
  { from: "ysalte", to: "amayon", type: "controls", label: "enslaves" },
  { from: "ysalte", to: "louis", type: "antagonizes", label: "targets for killing Ines" },
  { from: "carl", to: "amayon", type: "quest", label: "organizes world quest to free" },
  { from: "amayon", to: "carl", type: "allied", label: "gratitude / shares info on Geyrun" },
  // Shi Maria
  { from: "donut", to: "shi_maria", type: "companion", label: "deckmaster / captures as totem" },
  { from: "shi_maria", to: "carl", type: "controls", label: "possesses / tattoos Eye on chest" },
  { from: "carl", to: "shi_maria", type: "companion", label: "bound via tattoo" },
  { from: "shi_maria", to: "li_jun", type: "antagonizes", label: "stabs out eye (via Carl)" },
  // Tserendolgor death
  { from: "tserendolgor", to: "carl", type: "quest", label: "donates gear / dies on Floor 8" },
  // Osvaldo
  { from: "osvaldo", to: "carl", type: "allied", label: "Floor 8 leaderboard ally" },
  // HeyZoos card
  { from: "donut", to: "heyzoos", type: "companion", label: "captured as T'Ghee card" },
];
